name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, you have submitted this PR on the Cashier Provider organization which is a read-only sub split of [cashier-provider/dev](https://github.com/cashier-provider/dev). Please submit your PR on the https://github.com/cashier-provider/dev repository.<br><br>Thanks!"
